apiVersion: v1
kind: Namespace
metadata:
  name: bigdata
---
# 1. SERVICE
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: bigdata
spec:
  selector:
    app: spark-master
  type: NodePort
  ports:
    - name: master-rpc
      port: 7077
      targetPort: 7077
    - name: web-ui
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
# 2. SPARK MASTER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: mintdata2-virtualbox
      containers:
        - name: spark-master
          image: apache/spark:3.5.0
          command:
            [
              "/opt/spark/bin/spark-class",
              "org.apache.spark.deploy.master.Master",
            ]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2500Mi"
              cpu: "1000m"
          env:
            - name: SPARK_DAEMON_MEMORY
              value: "800m"

---
# 3. SPARK WORKER (SAFE MODE: 3 CORES - 5GB RAM)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      nodeSelector:
        kubernetes.io/hostname: mintdata2-virtualbox

      volumes:
        - name: spark-worker-data
          hostPath:
            path: /tmp/spark-worker-data
            type: DirectoryOrCreate

      containers:
        - name: spark-worker
          image: apache/spark:3.5.0
          command:
            [
              "/opt/spark/bin/spark-class",
              "org.apache.spark.deploy.worker.Worker",
              "spark://spark-master-svc:7077",
            ]
          volumeMounts:
            - name: spark-worker-data
              mountPath: /opt/spark/work

          # --- CẤU HÌNH AN TOÀN ---
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              # Giới hạn container ở mức 5.5GB (để lại 2.5GB cho OS)
              memory: "5500Mi"
              # Giới hạn CPU ở 3.5 Core (để lại 0.5 Core cho OS thở)
              cpu: "3500m"

          env:
            # Spark chỉ được dùng 4.5GB để cấp cho Executor
            - name: SPARK_WORKER_MEMORY
              value: "4500m"
            # Spark chỉ được dùng 3 Core (Đủ cho 1 Streaming + 1 Batch)
            - name: SPARK_WORKER_CORES
              value: "3"
