apiVersion: v1
kind: Namespace
metadata:
  name: bigdata
---
# 1. Service
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: bigdata
spec:
  selector:
    app: spark-master
  type: NodePort
  ports:
    - name: master-rpc
      port: 7077
      targetPort: 7077
    - name: web-ui
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
# 2. Spark Master
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: mintdata2-virtualbox

      containers:
        - name: spark-master
          image: apache/spark:3.5.0
          command:
            [
              "/opt/spark/bin/spark-class",
              "org.apache.spark.deploy.master.Master",
            ]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          # --- Cấu hình Ram ---
          resources:
            requests:
              memory: "512Mi" # Xin tối thiểu
              cpu: "200m" # Xin 0.2 Core
            limits:
              memory: "1200Mi" # Tối đa 1.2 GB (Đủ cho Driver + Overhead)
              cpu: "500m" # Tối đa 0.5 Core
          # ------------------------------
          env:
            - name: SPARK_DAEMON_MEMORY
              value: "800m" # Giảm Heap Java xuống 800MB để vừa vặn Container 1.2GB

---
# 3. Spark Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      nodeSelector:
        kubernetes.io/hostname: mintdata2-virtualbox

      containers:
        - name: spark-worker
          image: apache/spark:3.5.0
          command:
            [
              "/opt/spark/bin/spark-class",
              "org.apache.spark.deploy.worker.Worker",
              "spark://spark-master-svc:7077",
            ]
          # --- Cấu hình Ram ---
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1500Mi" # Tối đa 1.5 GB
              cpu: "1000m" # Tối đa 1 Core
          # ------------------------------
          env:
            - name: SPARK_WORKER_MEMORY
              value: "1024m" # Heap Java là 1GB (Để dành 500MB cho Overhead)
            - name: SPARK_WORKER_CORES
              value: "1"
